### ISSUE TITLE
.timeout Unhandled Promise Rejection

### ISSUE THREAD

**Issue by mrjackwills** [JimmyLaurent/x-ray-scraper#1]
### Subject of the issue
Using, and invoking , a .timeout results in an UnhandledPromiseRejectionWarning: Error: job timed out

### Your environment

Node version : v8.11.2
NPM version : 6.1.0

### Steps to reproduce

let Xray = require('x-ray-scraper');

async function testTimeout(){
    try{
        const title = await Xray.timeout(1)('http://google.com', 'title');
        console.log(title);
    }catch(err){
        console.log('Serious Error')
    }
};
testTimeout();

### Expected behaviour
'Serious Error' logged to console

### Actual behaviour
(node:13800) UnhandledPromiseRejectionWarning: Error: job timed out

using 

Xray.timeout(1)('http://google.com', 'title')
  .then(function(title){
    console.log(title);
  }).catch((err) => console.log('Serious Error'));

Results in 'Serious Error' being logged to console,

**Comment by JimmyLaurent** [comment]
Fixed in 3.0.5
